// -----------------------------------------------------------------------------
// GENERATED BY CSCM CLI
// Ce fichier contient des ancres (ex: // {{anchor}}) utilisees par le CLI
// pour injecter des modules (Social, Email). Ne les effacez pas si vous
// souhaitez pouvoir ajouter des fonctionnalites via la commande "cscm auth".
// -----------------------------------------------------------------------------

import 'package:dartz/dartz.dart';
// {{auth_repo_impl_imports_anchor}}

import 'package:supabase_flutter/supabase_flutter.dart';

// {{auth_repo_impl_imports_anchor}}
import 'package:e_tantana/core/error/exceptions.dart';
import 'package:e_tantana/core/error/failures.dart';
import 'package:e_tantana/core/network/network_info.dart';
import 'package:e_tantana/core/utils/typedef/typedefs.dart';
import 'package:e_tantana/features/auth/data/source/auth_remote_source.dart';
import 'package:e_tantana/features/auth/domain/entity/auth_entity.dart';
import 'package:e_tantana/features/auth/domain/repository/auth_repository.dart';

class AuthRepositoryImpl implements AuthRepository {
  final AuthRemoteSource _remoteSource;
  final NetworkInfo _networkInfo;

  AuthRepositoryImpl(this._remoteSource, this._networkInfo);

  // --- SESSION MANAGEMENT (Base) ---

  @override
  ResultFuture<AuthEntity?> getCurrentUser() async {
    try {
      final user = _remoteSource.getCurrentUser();
      return Right(user);
    } catch (e) {
      return Left(UnexceptedFailure(e.toString(), "500"));
    }
  }

  @override
  Stream<AuthEntity?> onAuthStateChanged() =>
      _remoteSource.onAuthStateChanged();

  @override
  ResultVoid signOut() async => await _execute(() => _remoteSource.signOut());

  // {{social_repo_impl_methods_anchor}}

  // --- SOCIAL AUTH ---

  @override
  ResultFuture<AuthEntity?> signInWithGoogle({
    required String webId,
    String? iosId,
  }) async {
    return await _execute(
      () => _remoteSource.signInWithGoogle(webId: webId, iosId: iosId),
    );
  }

  // {{social_repo_impl_methods_anchor}}

  // {{email_repo_impl_methods_anchor}}

  // --- EMAIL & SECURITY ---

  @override
  ResultFuture<AuthEntity> signUpWithEmail(String e, String p) async {
    return await _execute(() => _remoteSource.signUpWithEmail(e, p));
  }

  @override
  ResultFuture<AuthEntity> signInWithEmail(String e, String p) async {
    return await _execute(() => _remoteSource.signInWithEmail(e, p));
  }

  @override
  ResultVoid sendOtp(String e) async {
    return await _execute(() => _remoteSource.sendOtp(e));
  }

  @override
  ResultFuture<AuthEntity> verifyOtp(String e, String c, OtpType type) async {
    return await _execute(() => _remoteSource.verifyOtp(e, c, type));
  }

  @override
  ResultVoid updatePassword(String newPassword) async {
    return await _execute(() => _remoteSource.updatePassword(newPassword));
  }

  // {{email_repo_impl_methods_anchor}}

  // --- HELPER DE GESTION D'ERREURS (Toujours inclus) ---

  Future<Either<Failure, T>> _execute<T>(Future<T> Function() action) async {
    if (await _networkInfo.isConnected) {
      try {
        final res = await action();
        return Right(res);
      } on ApiException catch (e) {
        return Left(ApiFailure.fromException(e));
      } catch (e) {
        return Left(UnexceptedFailure(e.toString(), "500"));
      }
    }
    return const Left(NetworkFailure("Pas de connexion Internet", "NET_001"));
  }
}
