// -----------------------------------------------------------------------------
// GENERATED BY CSCM CLI
// Ce fichier contient des ancres (ex: // {{anchor}}) utilisees par le CLI
// pour injecter des modules (Social, Email). Ne les effacez pas si vous
// souhaitez pouvoir ajouter des fonctionnalites via la commande "cscm auth".
// -----------------------------------------------------------------------------

import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:e_tantana/features/auth/data/model/auth_model.dart';
import 'package:e_tantana/features/auth/data/source/auth_remote_source.dart';

// {{auth_imports_anchor}}

import 'package:e_tantana/features/auth/data/source/social_auth_service.dart';

import 'package:e_tantana/features/auth/data/source/email_auth_service.dart';

// {{auth_imports_anchor}}

class AuthRemoteSourceImpl implements AuthRemoteSource {
  final SupabaseClient _client;

  // {{auth_fields_anchor}}

  final SocialAuthService _socialService;

  final EmailAuthService _emailService;

  // {{auth_fields_anchor}}

  AuthRemoteSourceImpl(
    this._client,

    // {{auth_constructor_anchor}}
    this._socialService,

    this._emailService,

    // {{auth_constructor_anchor}}
  );

  // --- SESSION MANAGEMENT (Base) ---

  @override
  bool hasActiveSession() {
    final session = _client.auth.currentSession;
    return session != null;
  }

  @override
  AuthModel? getCurrentUser() {
    final user = _client.auth.currentUser;
    return user != null ? AuthModel.fromSupabase(user) : null;
  }

  @override
  Stream<AuthModel?> onAuthStateChanged() {
    return _client.auth.onAuthStateChange.map((event) {
      final user = event.session?.user;
      return user != null ? AuthModel.fromSupabase(user) : null;
    });
  }

  @override
  Future<void> signOut() async {
    await _client.auth.signOut();
  }

  // {{social_methods_impl_anchor}}

  // --- SOCIAL AUTH (Delegation) ---

  @override
  Future<AuthModel?> signInWithGoogle({
    required String webId,
    String? iosId,
  }) async {
    return await _socialService.signInWithGoogle(
      webClientId: webId,
      iosClientId: iosId,
    );
  }

  // {{social_methods_impl_anchor}}

  // {{email_methods_impl_anchor}}

  // --- EMAIL & SECURITY (Delegation) ---

  @override
  Future<AuthModel> signUpWithEmail(String e, String p) async {
    return await _emailService.signUp(e, p);
  }

  @override
  Future<AuthModel> signInWithEmail(String e, String p) async {
    return await _emailService.signIn(e, p);
  }

  @override
  Future<void> sendOtp(String e) async {
    return await _emailService.sendPasswordResetOtp(e);
  }

  @override
  Future<AuthModel> verifyOtp(String e, String c, OtpType type) async {
    return await _emailService.verifyOtp(e, c, type);
  }

  @override
  Future<void> updatePassword(String newPassword) async {
    return await _emailService.updatePassword(newPassword);
  }

  // {{email_methods_impl_anchor}}
}
