// -----------------------------------------------------------------------------
// GENERATED BY CSCM CLI
// Ce fichier contient des ancres (ex: // {{anchor}}) utilisees par le CLI
// pour injecter des modules (Social, Email). Ne les effacez pas si vous
// souhaitez pouvoir ajouter des fonctionnalites via la commande "cscm auth".
// -----------------------------------------------------------------------------

import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:e_tantana/features/auth/data/model/auth_model.dart';

abstract class AuthRemoteSource {
  // --- SESSION (Base) ---
  AuthModel? getCurrentUser();
  Stream<AuthModel?> onAuthStateChanged();
  Future<void> signOut();

  // {{social_methods_anchor}}

  // --- SOCIAL ---
  Future<AuthModel?> signInWithGoogle({required String webId, String? iosId});

  // {{social_methods_anchor}}

  // {{email_methods_anchor}}

  // --- EMAIL & SECURITY ---
  Future<AuthModel> signUpWithEmail(String e, String p);
  Future<AuthModel> signInWithEmail(String e, String p);
  Future<void> sendOtp(String e);
  Future<AuthModel> verifyOtp(String e, String c, OtpType type);
  Future<void> updatePassword(String newPassword);

  // {{email_methods_anchor}}
}
