// -----------------------------------------------------------------------------
// GENERATED BY CSCM CLI
// Ce fichier contient des ancres (ex: // {{anchor}}) utilisees par le CLI 
// pour injecter des modules (Social, Email). Ne les effacez pas si vous 
// souhaitez pouvoir ajouter des fonctionnalites via la commande "cscm auth".
// -----------------------------------------------------------------------------

import 'package:e_tantana/core/actions/app_action.dart';

sealed class AuthActions implements AppAction {}

// --- SESSION MANAGEMENT (Base) ---

class LoginAction extends AuthActions {
  @override String get errorMessage => "Erreur de connexion";
  @override bool get isWriteAction => true;
  @override String get successMessage => "Bienvenue !";
}

class LogoutAction extends AuthActions {
  @override String get errorMessage => "Erreur de deconnexion";
  @override bool get isWriteAction => true;
  @override String get successMessage => "Session terminee. A bientot !";
}

// {{social_actions_anchor}}

// --- SOCIAL AUTH ACTIONS ---
// Vous pouvez ajouter ici des actions specifiques au Social si besoin.

// {{social_actions_anchor}}

// {{email_actions_anchor}}

// --- EMAIL & SECURITY ---

class SignUpAction extends AuthActions {
  @override String get errorMessage => "Impossible de creer le compte";
  @override bool get isWriteAction => true;
  @override String get successMessage => "Compte cree avec succes !";
}

class SendOtpAction extends AuthActions {
  @override String get errorMessage => "Erreur lors de l'envoi du code";
  @override bool get isWriteAction => true;
  @override String get successMessage => "Le code a ete envoye sur votre email.";
}

class VerifyOtpAction extends AuthActions {
  @override String get errorMessage => "Code invalide ou expire";
  @override bool get isWriteAction => true;
  @override String get successMessage => "Code verifie avec succes.";
}

class UpdatePasswordAction extends AuthActions {
  @override String get errorMessage => "Erreur lors de la mise a jour du mot de passe";
  @override bool get isWriteAction => true;
  @override String get successMessage => "Mot de passe modifie avec succes !";
}

// {{email_actions_anchor}}