// -----------------------------------------------------------------------------
// GENERATED BY CSCM CLI
// Ce fichier contient des ancres (ex: // {{anchor}}) utilisees par le CLI
// pour injecter des modules (Social, Email). Ne les effacez pas si vous
// souhaitez pouvoir ajouter des fonctionnalites via la commande "cscm auth".
// -----------------------------------------------------------------------------

import 'package:flutter_riverpod/flutter_riverpod.dart';
// {{auth_controller_imports_anchor}}

import 'package:supabase_flutter/supabase_flutter.dart';

// {{auth_controller_imports_anchor}}
import 'package:e_tantana/core/di/injection_container.dart';
import 'package:e_tantana/core/error/failures.dart';
import 'package:e_tantana/features/auth/domain/actions/auth_actions.dart';
import 'package:e_tantana/features/auth/domain/usecases/auth_usecases.dart';
import 'package:e_tantana/features/auth/presentation/states/auth_states.dart';

class AuthController extends StateNotifier<AuthStates> {
  final AuthUsecases _authUsecases;

  AuthController(this._authUsecases) : super(const AuthStates()) {
    checkCurrentUser();
  }

  // --- SESSION MANAGEMENT (Base) ---

  Future<void> checkCurrentUser() async {
    final res = await _authUsecases.getCurrentUser();
    res.fold((_) => null, (user) {
      if (user != null) state = state.copyWith(user: user);
    });
  }

  Future<void> logout() async {
    final action = LogoutAction();
    _setLoadingState(action: action);

    final res = await _authUsecases.signOut();

    res.fold(
      (error) => _setError(error: error, action: action),
      (_) => state = const AuthStates(),
    );
  }

  // {{social_controller_methods_anchor}}

  // --- SOCIAL AUTH ---

  Future<void> loginWithGoogle({required String webId, String? iosId}) async {
    final action = LoginAction();
    _setLoadingState(action: action);

    final res = await _authUsecases.signInWithGoogle(
      webId: webId,
      iosId: iosId,
    );

    res.fold(
      (error) => _setError(error: error, action: action),
      (user) =>
          state = state.copyWith(
            isLoading: false,
            isClearError: true,
            user: user,
            action: action,
          ),
    );
  }

  // {{social_controller_methods_anchor}}

  // {{email_controller_methods_anchor}}

  // --- EMAIL & SECURITY ---

  Future<void> registerWithEmail(String email, String password) async {
    final action = SignUpAction();
    _setLoadingState(action: action);

    final res = await _authUsecases.signUpWithEmail(email, password);

    res.fold(
      (error) => _setError(error: error, action: action),
      (user) =>
          state = state.copyWith(
            isLoading: false,
            isClearError: true,
            user: user,
            action: action,
          ),
    );
  }

  Future<void> loginWithEmail(String email, String password) async {
    final action = LoginAction();
    _setLoadingState(action: action);

    final res = await _authUsecases.signInWithEmail(email, password);

    res.fold(
      (error) => _setError(error: error, action: action),
      (user) =>
          state = state.copyWith(
            isLoading: false,
            isClearError: true,
            user: user,
            action: action,
          ),
    );
  }

  Future<void> requestOtp(String email) async {
    final action = SendOtpAction();
    _setLoadingState(action: action);

    final res = await _authUsecases.sendOtp(email);

    res.fold(
      (error) => _setError(error: error, action: action),
      (_) =>
          state = state.copyWith(
            isLoading: false,
            isClearError: true,
            action: action,
          ),
    );
  }

  Future<void> verifyOtpCode(String email, String code, OtpType type) async {
    final action = VerifyOtpAction();
    _setLoadingState(action: action);

    final res = await _authUsecases.verifyOtp(email, code, type);

    res.fold(
      (error) => _setError(error: error, action: action),
      (user) =>
          state = state.copyWith(
            isLoading: false,
            isClearError: true,
            user: user,
            action: action,
          ),
    );
  }

  Future<void> changePassword(String newPassword) async {
    final action = UpdatePasswordAction();
    _setLoadingState(action: action);

    final res = await _authUsecases.updatePassword(newPassword);

    res.fold(
      (error) => _setError(error: error, action: action),
      (_) =>
          state = state.copyWith(
            isLoading: false,
            isClearError: true,
            action: action,
          ),
    );
  }

  // {{email_controller_methods_anchor}}

  // --- UTILITAIRES INTERNES ---

  void _setLoadingState({required AuthActions action}) {
    state = state.copyWith(isLoading: true, action: action);
  }

  void _setError({required Failure error, required AuthActions action}) {
    state = state.copyWith(isLoading: false, error: error, action: action);
  }
}

// --- PROVIDER ---
final authControllerProvider =
    StateNotifierProvider<AuthController, AuthStates>((ref) {
      return AuthController(sl<AuthUsecases>());
    });
