// -----------------------------------------------------------------------------
// GENERATED BY CSCM CLI
// Ce fichier contient des ancres (ex: // {{anchor}}) utilisees par le CLI 
// pour injecter des modules (Social, Email). Ne les effacez pas si vous 
// souhaitez pouvoir ajouter des fonctionnalites via la commande "cscm auth".
// -----------------------------------------------------------------------------

// {{auth_usecases_imports_anchor}}

import 'package:supabase_flutter/supabase_flutter.dart';

import 'package:e_tantana/core/utils/typedef/typedefs.dart';
import 'package:e_tantana/features/auth/domain/entity/auth_entity.dart';
import 'package:e_tantana/features/auth/domain/repository/auth_repository.dart';
// {{auth_usecases_imports_anchor}}

class AuthUsecases {
  final AuthRepository _repo;
  AuthUsecases(this._repo);

  // --- SESSION MANAGEMENT (Base) ---
  ResultFuture<AuthEntity?> getCurrentUser() => _repo.getCurrentUser();
  Stream<AuthEntity?> onAuthStateChanged() => _repo.onAuthStateChanged();
  ResultVoid signOut() => _repo.signOut();
  
  // {{social_usecases_methods_anchor}}

  // --- SOCIAL AUTH ---
  ResultFuture<AuthEntity?> signInWithGoogle({required String webId, String? iosId}) => 
      _repo.signInWithGoogle(webId: webId, iosId: iosId);

  // {{social_usecases_methods_anchor}}

  // {{email_usecases_methods_anchor}}

  // --- EMAIL & SECURITY ---
  ResultFuture<AuthEntity> signUpWithEmail(String e, String p) => 
      _repo.signUpWithEmail(e, p);

  ResultFuture<AuthEntity> signInWithEmail(String e, String p) => 
      _repo.signInWithEmail(e, p);

  ResultVoid sendOtp(String e) => _repo.sendOtp(e);

  ResultFuture<AuthEntity> verifyOtp(String e, String c, OtpType type) => 
      _repo.verifyOtp(e, c, type);

  ResultVoid updatePassword(String newPassword) => _repo.updatePassword(newPassword);

  // {{email_usecases_methods_anchor}}
}