// -----------------------------------------------------------------------------
// GENERATED BY CSCM CLI
// Ce fichier contient des ancres (ex: // {{anchor}}) utilisees par le CLI
// pour injecter des modules (Social, Email). Ne les effacez pas si vous
// souhaitez pouvoir ajouter des fonctionnalites via la commande "cscm auth".
// -----------------------------------------------------------------------------

// {{auth_repo_imports_anchor}}

import 'package:supabase_flutter/supabase_flutter.dart';

import 'package:e_tantana/core/utils/typedef/typedefs.dart';
import 'package:e_tantana/features/auth/domain/entity/auth_entity.dart';
// {{auth_repo_imports_anchor}}

abstract class AuthRepository {
  // --- SESSION MANAGEMENT (Base) ---
  ResultFuture<AuthEntity?> getCurrentUser();
  Stream<AuthEntity?> onAuthStateChanged();
  ResultVoid signOut();

  // {{social_repo_methods_anchor}}

  // --- SOCIAL AUTH ---
  ResultFuture<AuthEntity?> signInWithGoogle({
    required String webId,
    String? iosId,
  });

  // {{social_repo_methods_anchor}}

  // {{email_repo_methods_anchor}}

  // --- EMAIL & SECURITY ---
  ResultFuture<AuthEntity> signUpWithEmail(String e, String p);
  ResultFuture<AuthEntity> signInWithEmail(String e, String p);
  ResultVoid sendOtp(String e);
  ResultFuture<AuthEntity> verifyOtp(String e, String c, OtpType type);
  ResultVoid updatePassword(String newPassword);

  // {{email_repo_methods_anchor}}
}
